### ISSUE TITLE
Unable to resolve user service

### ISSUE THREAD

**Issue by braaar** [indivorg/runner#19]
Getting this error when trying to run local dev. Changes were made to the infrastructure which may require updating something about how the runner finds each service?

`[Nest] 13131  - 12/02/2021, 5:46:04 PM   ERROR [ExceptionsHandler] 14 UNAVAILABLE: Name resolution failed for target dns:user-v1:8080
Error: 14 UNAVAILABLE: Name resolution failed for target dns:user-v1:8080
    at Object.callErrorFromStatus (/Users/braaar/Kode/indiv/service-api/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/braaar/Kode/indiv/service-api/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/Users/braaar/Kode/indiv/service-api/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/Users/braaar/Kode/indiv/service-api/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /Users/braaar/Kode/indiv/service-api/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)`

**Comment by braaar** [comment]
fixed by https://github.com/indivorg/infra-app/commit/291f5b78e109ca4719a07f26371b9fee42f22964

**Comment by braaar** [comment]
The issue was not resolved after all.

**Comment by simenandre** [comment]
This is not an issue with indivorg/runner. Closing.
